"""Submodule for the `SubConfig` `Loader`, which can be used to
create/configure hierarchical object structures in various ways."""

from .loader import Loader
from .utils import ParseError

class ListConfig(Loader):
    """Loader for lists of `Configurable`s. This loader takes a single key from
    its configuration dictionary, which must be a list of dictionaries. These
    dictionaries are normally used to configure the target `Configurable`
    classes. Alternatively, the dictionaries can again contain a list of
    dictionaries with a specific name which are parsed into the `Configurable`s
    instead, using the original dictionary as a prototype.

    The class is constructed with a reference to its parent as its first and
    only positional argument. Any keys that have been parsed before can be read
    from this for contextual information."""

    def __init__(self, key, doc, configurable, subkey=None):
        super().__init__(key, doc)
        self._configurable = configurable
        self._subkey = subkey

    @property
    def subkey(self):
        """The prototype subkey for this loader, or `None` if this feature is
        disabled."""
        return self._subkey

    def markdown(self):
        """Yields markdown documentation for all the keys that this loader can
        make sense of as `(key, markdown)` tuples."""
        markdown = [self.doc]

        if self.subkey is not None:
            markdown.append(
                'If the `%s` key is present in a configuration dictionary, it '
                'is recursively interpreted as a list of dictionaries, similar '
                'to this key, instead of being parsed directly. Any additional '
                'keys in the dictionary are then used as default values for '
                'the subdictionaries. For example,' % self.subkey)
            markdown.append(
                '```\n'
                '%s:\n'
                '- a: 1\n'
                '  b: 2\n'
                '  c: 3\n'
                '  %s:\n'
                '  - a: 5\n'
                '  - d: 4\n'
                '```' % (self.key, self.subkey))
            markdown.append('is equivalent to')
            markdown.append(
                '```\n'
                '%s:\n'
                '- a: 5\n'
                '  b: 2\n'
                '  c: 3\n'
                '- a: 1\n'
                '  b: 2\n'
                '  c: 3\n'
                '  d: 4\n'
                '```' % self.key)
            markdown.append(
                'This can be useful for specifying repetetive structures.')

        markdown.append(
            'This key is optional. Not specifying it is equivalent to '
            'specifying an empty list.')

        yield self.key, markdown

    def markdown_more(self):
        """Yields or returns a list of `@configurable` classes that must be
        documented in addition because the docs generated by `markdown()` refer
        to them."""
        yield self._configurable

    def _handle_list(self, config_list, parent, prototype=None):
        """Handles a list of subconfigs, yielding the deserialized objects."""

        # Verify that we got a list.
        if not isinstance(config_list, list):
            ParseError.invalid('', config_list, [])

        for index, subdict in enumerate(config_list):
            with ParseError.wrap(index):

                # Verify that the list entry is a dictionary.
                if not isinstance(subdict, dict):
                    ParseError.invalid('', config_list, [])

                # Merge the dictionary with the prototype, if there is one.
                if prototype:
                    updated_prototype = prototype.copy()
                    updated_prototype.update(subdict)
                    subdict = updated_prototype

                # Handle the next level of prototypes, if there is one.
                if self.subkey is not None and self.subkey in subdict:
                    sublist = subdict.pop(self.subkey)
                    with ParseError.wrap(self.subkey):
                        generator = self._handle_list(sublist, parent, subdict)
                    for item in generator:
                        yield item
                    continue

                # Pass the final dict to the configurable for deserialization.
                yield self._configurable(parent, subdict)

    def deserialize(self, dictionary, parent):
        """`ListConfig` deserializer. See `Loader.deserialize()` for more
        info."""
        with ParseError.wrap(self.key):
            return list(self._handle_list(dictionary.pop(self.key, []), parent))

    def serialize(self, dictionary, value):
        """`ListConfig` serializer. See `Loader.serialize()` for more info."""
        dictionary[self.key] = [item.serialize() for item in value]


def listconfig(method):
    """Method decorator for configuring a list of `configurable`-annotated
    objects. The annotated method is called with zero arguments (not even
    `self`) to get the class that is to be constructed. The name of the key is
    set to the name of the method, and the markdown documentation for the key
    is set to the method's docstring."""
    return ListConfig(method.__name__, method.__doc__, method())


def protolistconfig(method):
    """Like `@listconfig`, but supports prototypes. The prototype key is set
    to the name of the method with `'sub'` prefixed to it."""
    return ListConfig(method.__name__, method.__doc__, method(), 'sub' + method.__name__)
