"""Submodule for the `Select` `Loader`. This loader works like a `SubConfig`,
but uses an additional key in the dictionary to select which configurable to
instantiate."""

import textwrap
from collections import OrderedDict
from .loader import Loader
from .utils import ParseError

class Select(Loader):
    """Loader for embedding `Configurable`s, with multiple different kinds of
    possible `Configurable` classes, based on an additional selection key.

    The class is constructed with a reference to its parent as its first
    and only positional argument. Any keys that have been parsed before can be
    read from this for contextual information."""

    def __init__(self, key, doc, config_options):
        super().__init__(key, doc)
        self._config_options = config_options

    def markdown(self):
        """Yields markdown documentation for all the keys that this loader can
        make sense of as `(key, markdown)` tuples."""
        markdown = [self.doc]

        markdown.append('This key can take the following values:')

        for value, (_, doc) in self._config_options.items():
            markdown.append(' - `%s`: %s' % (
                value, textwrap.dedent(doc).replace('\n', '\n   ')))

        yield self.friendly_key, markdown

    def markdown_more(self):
        """Yields or returns a list of `@configurable` classes that must be
        documented in addition because the docs generated by `markdown()` refer
        to them."""
        for configurable, _ in self._config_options:
            yield configurable

    def deserialize(self, dictionary, parent, path=()):
        """`Select` deserializer. See `Loader.deserialize()` for more
        info."""
        selection = self.pop_dict(dictionary, self.key, path)
        configurable, _ = self._config_options.get(selection, (None, None))
        if configurable is None:
            raise ParseError('%s has unknown value `%r`' % (
                self.friendly_path(path), selection))
        return selection, configurable.from_dict(dictionary, parent)

    def serialize(self, dictionary, value):
        """`Select` serializer. See `Loader.serialize()` for more info."""
        selection, item = value
        dictionary[self.friendly_key] = selection
        item.to_dict(dictionary)


def select(method):
    """Method decorator for configuring a `configurable`-annotated class
    selected through another configuration value. The annotated method is
    called with zero arguments (not even `self`) to generate/yield
    `(value, configurable, doc)` three-tuples, where `value` is the unique
    value that the user must specify to select `configurable`, and `doc` is the
    documentation associated with this option. The method is transformed to a
    property that allows the object type and the constructed configurable
    instance to be accessed as a `(selection, instance)` two-tuple."""
    return Select(
        method.__name__, method.__doc__, OrderedDict((
            (value, (configurable, doc))
            for value, configurable, doc in method())))
